name: calling-mainwf
run-name: run-name-calling-mainwf

on:
  push:
  workflow_dispatch:
    inputs:
      allure:
        type: boolean
        description: Generar reporte Allure
        default: true
      extent:
        type: boolean
        description: Generar reporte Extent
        default: true
      cucumber:
        type: boolean
        description: Generar reporte Cucumber
        default: true
      recorder:
        type: boolean
        description: Grabar la ejecución
        default: true
jobs:
  call-workflow-passing-data:
    uses: QuiqueBarberan/variables/.github/workflows/main_wf.yml@master
    with:
      allure: ${{ github.event.inputs.allure == true }}
      extent: ${{ github.event.inputs.extent == true }}
      cucumber: ${{ github.event.inputs.cucumber == true }}
      recorder: ${{ github.event.inputs.recorder == true }}
