name: called

on:
  workflow_call:
    inputs:
      called:
        type: boolean
        default: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'init'
      - run: echo 'inputs.called'
        if: ${{ inputs.called }}
      - run: echo 'inputs.called == 'true''
        if: ${{ inputs.called == 'true' }}
      - run: echo 'inputs.called == true'
        if: ${{ inputs.called == true }}
      - run: echo 'end'
