name: called

on:
  workflow_call:
    inputs:
      called:
        type: boolean
        default: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'init'
      - run: echo 'dentro'
        if: ${{ inputs.called }}
      - run: echo 'end'
