name: Changing vars

on:
  workflow_dispatch:
#env:
#  REPO_ID: '123456789'

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_TOKEN: ${{ secrets.SECRET1 }}
    steps:
      - name: Use REPO_ID
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
      - id: getrepoid
        run: |
          echo REPO_ID=$(gh api -H "Accept: application/vnd.github+json" repos/QuiqueBarberan/${{ github.event.repository.name }} | jq .id) >> $GITHUB_ENV
      - id: echorepoid
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
      - id: getbuildnumber
        run: |
          echo BUILD_NUMBER=$(gh api -H "Accept: application/vnd.github+json" repositories/${{ env.REPO_ID }}/environments/dev/variables/BUILD_NUMBER | jq .value) >> $GITHUB_ENV
      - id: echobuildnumber
        run: |
          BUILD_NUMBER=`expr ${{ env.BUILD_NUMBER }} + 1`
          echo BUILD_NUMBER
          echo BUILD_NUMBER=$($BUILD_NUMBER) >> GITHUB_ENV
          echo ${{ BUILD_NUMBER }}
          gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repositories/${{ env.REPO_ID }}/environments/dev/variables/BUILD_NUMBER -f name='BUILD_NUMBER' -f value='${{ env.BUILD_NUMBER }}'
