name: Changing vars

on:
  workflow_dispatch:
env:
  REPO_ID: '123456789'

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_TOKEN: ${{ secrets.SECRET1 }}
    steps:
      - name: Use REPO_ID
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
      - id: stepid
        run: |
          echo REPO_ID=$(gh api -H "Accept: application/vnd.github+json" repos/QuiqueBarberan/${{ github.event.repository.name }} | jq .id) >> $GITHUB_ENV
      - run: |
          echo "REPO_ID value is as repo-env-value: ${{ env.REPO_ID }}"
