name: Changing vars

on:
  workflow_dispatch:
env:
  REPO_ID: '123456789'

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_TOKEN: ${{ secrets.SECRET1 }}
    outputs:
      output_time: ${{ steps.stepid.outputs.time }}
    steps:
      - name: Use MY_VAR1
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
      - id: stepid
        run: |
          echo $(gh api -H "Accept: application/vnd.github+json" repos/PrisaMedia/${{ github.event.repository.name }})
          jq .id
      - name: Set REPO_ID
        run: |
          echo "REPO_ID=${{ steps.stepid.outputs.time }}" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use MY_VAR2
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
