name: Changing vars

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - test
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_TOKEN: ${{ secrets.SECRET1 }}
    steps:
      - name: Retrieve Environment Name
        run: |
          echo ${{ github.event.repository.name }}
          echo ${{ tojson(github.event.org) }}
        
      - name: getrepoid
        run: |
          echo REPO_ID=$(gh api -H "Accept: application/vnd.github+json" repos/QuiqueBarberan/${{ github.event.repository.name }} | jq .id) >> $GITHUB_ENV
      - name: echorepoid
        run: |
          echo "REPO_ID value is: ${{ env.REPO_ID }}"
      - name: getbuildnumber
        run: |
          echo BUILD_NUMBER=$(gh api -H "Accept: application/vnd.github+json" repositories/${{ env.REPO_ID }}/environments/${{ inputs.environment }}/variables/BUILD_NUMBER | jq .value) >> $GITHUB_ENV
      - name: echobuildnumber
        run: |
          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
          BUILD_NUMBER=${BUILD_NUMBER//\"/}
          BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo $BUILD_NUMBER
          gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repositories/${{ env.REPO_ID }}/environments/dev/variables/BUILD_NUMBER -f name='BUILD_NUMBER' -f value=$BUILD_NUMBER
