on:
  workflow_dispatch:

env:
  TIEMPO: 123456

jobs:
  Echo-On-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: "mostrar valor"
        run: echo $TIEMPO
      - name: "mostrar valor"
        run: echo "TIEMPO=654321" >> $GITHUB_ENV
      - name: "mostrar valor despues"
        run: echo $TIEMPO
