on:
  workflow_dispatch:

jobs:
  JOB1:
    runs-on: ubuntu-latest
    outputs:
      EXECUTION_TIME: ${{ steps.steptime.outputs.time }}
    steps:
      - name: Crear Valor
        id: steptime
        run: echo "time=$(date '+%Y%m%d%H%M')" >> GITHUB_OUTPUT
        
      - name: Mostrar valor
        id: showvalue
        run: echo ${{ steps.steptimeoutputs.time }}

  JOB2:
    needs: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar valor despues
        id: showvalue
        run: echo ${{ steps.steptimeoutputs.time }}
