name: DateTime yml

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_time: ${{ steps.stepid.outputs.time }}
    steps:
      - id: stepid
        run: echo "time=$(date '+%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"
      - name: show1
        run: echo $time
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          EXECUTION_TIME: ${{needs.job1.outputs.output_time}}
        run: echo "$EXECUTION_TIME"
