name: test environ

on:
  workflow_dispatch:
    inputs:
      env:
        options:
        - dev
        - test
        type: choice
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Github Workspace
        run: echo ${{ github.github_workspace }}
      - run: echo ${{ vars.VAR1 }}
      - run: echo ${{ vars.VAR2 }}
