name: testenviron

on:
  workflow_dispatch:
    inputs:
      env:
        options:
        - dev
        - test
        type: choice
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo ${{ vars.VAR1 }}
      - run: echo ${{ vars.VAR2 }}
